services:
  fl-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    ports:
      - "8080:8080"
    networks:
      - fl_star

  pi-client-1:
    build:
      context: .
      dockerfile: Dockerfile
      target: client
    environment:
      - SERVER_ADDRESS=fl-server:8080
      - CLIENT_NAME=pi-client-1
    ports:
      - "8000:8000"
    volumes:
      - ./data/pi-client-1:/app/local_data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - fl_star
    depends_on:
      - fl-server

  pi-client-2:
    build:
      context: .
      dockerfile: Dockerfile
      target: client
    environment:
      - SERVER_ADDRESS=fl-server:8080
      - CLIENT_NAME=pi-client-2
    ports:
      - "8001:8001"
    volumes:
      - ./data/pi-client-2:/app/local_data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      networks:
        - fl_star
      depends_on:
        - fl-server

  networks:
    fl_star:
      driver: bridge


